"""add_legal_3_0_new_tables_firm_clause_case_risk_litigation

Revision ID: 6cee570342e7
Revises: 707ef8588e61
Create Date: 2025-09-30 13:50:10.907926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cee570342e7'
down_revision: Union[str, Sequence[str], None] = '707ef8588e61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
